databases:
  - name: Gift_DB
    databaseName: hiroto_db
    user: Gift
    region: singapore

services:
  - type: web
    name: Gift
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Gift_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

